######################################################################
# Automatically generated by qmake (3.0) Sun Apr 27 22:39:17 2014
######################################################################

TEMPLATE = app
TARGET = client
INCLUDEPATH += . header
QT += widgets
QT += network
unix:OBJECTS_DIR = objs/

# Input
HEADERS += header/MainWindow.hpp header/Login.hpp header/Network.hpp
SOURCES += srcs/main.cpp srcs/MainWindow.cpp srcs/Login.cpp srcs/Network.cpp
